#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachHang
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKH")]
	public partial class QLKHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblGiaoDich(tblGiaoDich instance);
    partial void UpdatetblGiaoDich(tblGiaoDich instance);
    partial void DeletetblGiaoDich(tblGiaoDich instance);
    partial void InserttblKhachHang(tblKhachHang instance);
    partial void UpdatetblKhachHang(tblKhachHang instance);
    partial void DeletetblKhachHang(tblKhachHang instance);
    partial void InserttblLichSuGiaoDich(tblLichSuGiaoDich instance);
    partial void UpdatetblLichSuGiaoDich(tblLichSuGiaoDich instance);
    partial void DeletetblLichSuGiaoDich(tblLichSuGiaoDich instance);
    partial void InserttblLoaiSanPham(tblLoaiSanPham instance);
    partial void UpdatetblLoaiSanPham(tblLoaiSanPham instance);
    partial void DeletetblLoaiSanPham(tblLoaiSanPham instance);
    partial void InserttblNhaCungCap(tblNhaCungCap instance);
    partial void UpdatetblNhaCungCap(tblNhaCungCap instance);
    partial void DeletetblNhaCungCap(tblNhaCungCap instance);
    partial void InserttblNhanVien(tblNhanVien instance);
    partial void UpdatetblNhanVien(tblNhanVien instance);
    partial void DeletetblNhanVien(tblNhanVien instance);
    partial void InserttblQuyen(tblQuyen instance);
    partial void UpdatetblQuyen(tblQuyen instance);
    partial void DeletetblQuyen(tblQuyen instance);
    partial void InserttblSanPham(tblSanPham instance);
    partial void UpdatetblSanPham(tblSanPham instance);
    partial void DeletetblSanPham(tblSanPham instance);
    partial void InserttblSanPhamGiaoDich(tblSanPhamGiaoDich instance);
    partial void UpdatetblSanPhamGiaoDich(tblSanPhamGiaoDich instance);
    partial void DeletetblSanPhamGiaoDich(tblSanPhamGiaoDich instance);
    partial void InserttblTaiKhoan(tblTaiKhoan instance);
    partial void UpdatetblTaiKhoan(tblTaiKhoan instance);
    partial void DeletetblTaiKhoan(tblTaiKhoan instance);
    #endregion
		
		public QLKHDataContext() : 
				base(global::QuanLiKhachHang.Properties.Settings.Default.QLKHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblGiaoDich> tblGiaoDiches
		{
			get
			{
				return this.GetTable<tblGiaoDich>();
			}
		}
		
		public System.Data.Linq.Table<tblKhachHang> tblKhachHangs
		{
			get
			{
				return this.GetTable<tblKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<tblLichSuGiaoDich> tblLichSuGiaoDiches
		{
			get
			{
				return this.GetTable<tblLichSuGiaoDich>();
			}
		}
		
		public System.Data.Linq.Table<tblLoaiSanPham> tblLoaiSanPhams
		{
			get
			{
				return this.GetTable<tblLoaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tblNhaCungCap> tblNhaCungCaps
		{
			get
			{
				return this.GetTable<tblNhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<tblNhanVien> tblNhanViens
		{
			get
			{
				return this.GetTable<tblNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tblQuyen> tblQuyens
		{
			get
			{
				return this.GetTable<tblQuyen>();
			}
		}
		
		public System.Data.Linq.Table<tblSanPham> tblSanPhams
		{
			get
			{
				return this.GetTable<tblSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tblSanPhamGiaoDich> tblSanPhamGiaoDiches
		{
			get
			{
				return this.GetTable<tblSanPhamGiaoDich>();
			}
		}
		
		public System.Data.Linq.Table<tblTaiKhoan> tblTaiKhoans
		{
			get
			{
				return this.GetTable<tblTaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGiaoDich")]
	public partial class tblGiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGD;
		
		private System.DateTime _NgayGiaoDich;
		
		private int _TienThanhToan;
		
		private int _DiemTich;
		
		private int _TienGiam;
		
		private int _TienKhachTra;
		
		private int _TienTraLai;
		
		private int _MaNV;
		
		private int _MaKH;
		
		private EntitySet<tblLichSuGiaoDich> _tblLichSuGiaoDiches;
		
		private EntitySet<tblSanPhamGiaoDich> _tblSanPhamGiaoDiches;
		
		private EntityRef<tblKhachHang> _tblKhachHang;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGDChanging(int value);
    partial void OnMaGDChanged();
    partial void OnNgayGiaoDichChanging(System.DateTime value);
    partial void OnNgayGiaoDichChanged();
    partial void OnTienThanhToanChanging(int value);
    partial void OnTienThanhToanChanged();
    partial void OnDiemTichChanging(int value);
    partial void OnDiemTichChanged();
    partial void OnTienGiamChanging(int value);
    partial void OnTienGiamChanged();
    partial void OnTienKhachTraChanging(int value);
    partial void OnTienKhachTraChanged();
    partial void OnTienTraLaiChanging(int value);
    partial void OnTienTraLaiChanged();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    #endregion
		
		public tblGiaoDich()
		{
			this._tblLichSuGiaoDiches = new EntitySet<tblLichSuGiaoDich>(new Action<tblLichSuGiaoDich>(this.attach_tblLichSuGiaoDiches), new Action<tblLichSuGiaoDich>(this.detach_tblLichSuGiaoDiches));
			this._tblSanPhamGiaoDiches = new EntitySet<tblSanPhamGiaoDich>(new Action<tblSanPhamGiaoDich>(this.attach_tblSanPhamGiaoDiches), new Action<tblSanPhamGiaoDich>(this.detach_tblSanPhamGiaoDiches));
			this._tblKhachHang = default(EntityRef<tblKhachHang>);
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGD
		{
			get
			{
				return this._MaGD;
			}
			set
			{
				if ((this._MaGD != value))
				{
					this.OnMaGDChanging(value);
					this.SendPropertyChanging();
					this._MaGD = value;
					this.SendPropertyChanged("MaGD");
					this.OnMaGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaoDich", DbType="DateTime2 NOT NULL")]
		public System.DateTime NgayGiaoDich
		{
			get
			{
				return this._NgayGiaoDich;
			}
			set
			{
				if ((this._NgayGiaoDich != value))
				{
					this.OnNgayGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoDich = value;
					this.SendPropertyChanged("NgayGiaoDich");
					this.OnNgayGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienThanhToan", DbType="Int NOT NULL")]
		public int TienThanhToan
		{
			get
			{
				return this._TienThanhToan;
			}
			set
			{
				if ((this._TienThanhToan != value))
				{
					this.OnTienThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TienThanhToan = value;
					this.SendPropertyChanged("TienThanhToan");
					this.OnTienThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemTich", DbType="Int NOT NULL")]
		public int DiemTich
		{
			get
			{
				return this._DiemTich;
			}
			set
			{
				if ((this._DiemTich != value))
				{
					this.OnDiemTichChanging(value);
					this.SendPropertyChanging();
					this._DiemTich = value;
					this.SendPropertyChanged("DiemTich");
					this.OnDiemTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienGiam", DbType="Int NOT NULL")]
		public int TienGiam
		{
			get
			{
				return this._TienGiam;
			}
			set
			{
				if ((this._TienGiam != value))
				{
					this.OnTienGiamChanging(value);
					this.SendPropertyChanging();
					this._TienGiam = value;
					this.SendPropertyChanged("TienGiam");
					this.OnTienGiamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienKhachTra", DbType="Int NOT NULL")]
		public int TienKhachTra
		{
			get
			{
				return this._TienKhachTra;
			}
			set
			{
				if ((this._TienKhachTra != value))
				{
					this.OnTienKhachTraChanging(value);
					this.SendPropertyChanging();
					this._TienKhachTra = value;
					this.SendPropertyChanged("TienKhachTra");
					this.OnTienKhachTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienTraLai", DbType="Int NOT NULL")]
		public int TienTraLai
		{
			get
			{
				return this._TienTraLai;
			}
			set
			{
				if ((this._TienTraLai != value))
				{
					this.OnTienTraLaiChanging(value);
					this.SendPropertyChanging();
					this._TienTraLai = value;
					this.SendPropertyChanged("TienTraLai");
					this.OnTienTraLaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tblKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGiaoDich_tblLichSuGiaoDich", Storage="_tblLichSuGiaoDiches", ThisKey="MaGD", OtherKey="MaGD")]
		public EntitySet<tblLichSuGiaoDich> tblLichSuGiaoDiches
		{
			get
			{
				return this._tblLichSuGiaoDiches;
			}
			set
			{
				this._tblLichSuGiaoDiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGiaoDich_tblSanPhamGiaoDich", Storage="_tblSanPhamGiaoDiches", ThisKey="MaGD", OtherKey="MaGD")]
		public EntitySet<tblSanPhamGiaoDich> tblSanPhamGiaoDiches
		{
			get
			{
				return this._tblSanPhamGiaoDiches;
			}
			set
			{
				this._tblSanPhamGiaoDiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblGiaoDich", Storage="_tblKhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tblKhachHang tblKhachHang
		{
			get
			{
				return this._tblKhachHang.Entity;
			}
			set
			{
				tblKhachHang previousValue = this._tblKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tblKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhachHang.Entity = null;
						previousValue.tblGiaoDiches.Remove(this);
					}
					this._tblKhachHang.Entity = value;
					if ((value != null))
					{
						value.tblGiaoDiches.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("tblKhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblGiaoDich", Storage="_tblNhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblGiaoDiches.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblGiaoDiches.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblLichSuGiaoDiches(tblLichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblGiaoDich = this;
		}
		
		private void detach_tblLichSuGiaoDiches(tblLichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblGiaoDich = null;
		}
		
		private void attach_tblSanPhamGiaoDiches(tblSanPhamGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblGiaoDich = this;
		}
		
		private void detach_tblSanPhamGiaoDiches(tblSanPhamGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblGiaoDich = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKhachHang")]
	public partial class tblKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private string _NamSinh;
		
		private string _CMND;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private string _Email;
		
		private int _DiemTichLuy;
		
		private string _LoaiKhachHang;
		
		private EntitySet<tblGiaoDich> _tblGiaoDiches;
		
		private EntitySet<tblLichSuGiaoDich> _tblLichSuGiaoDiches;
		
		private EntitySet<tblTaiKhoan> _tblTaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNamSinhChanging(string value);
    partial void OnNamSinhChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiemTichLuyChanging(int value);
    partial void OnDiemTichLuyChanged();
    partial void OnLoaiKhachHangChanging(string value);
    partial void OnLoaiKhachHangChanged();
    #endregion
		
		public tblKhachHang()
		{
			this._tblGiaoDiches = new EntitySet<tblGiaoDich>(new Action<tblGiaoDich>(this.attach_tblGiaoDiches), new Action<tblGiaoDich>(this.detach_tblGiaoDiches));
			this._tblLichSuGiaoDiches = new EntitySet<tblLichSuGiaoDich>(new Action<tblLichSuGiaoDich>(this.attach_tblLichSuGiaoDiches), new Action<tblLichSuGiaoDich>(this.detach_tblLichSuGiaoDiches));
			this._tblTaiKhoans = new EntitySet<tblTaiKhoan>(new Action<tblTaiKhoan>(this.attach_tblTaiKhoans), new Action<tblTaiKhoan>(this.detach_tblTaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this.OnNamSinhChanging(value);
					this.SendPropertyChanging();
					this._NamSinh = value;
					this.SendPropertyChanged("NamSinh");
					this.OnNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemTichLuy", DbType="Int NOT NULL")]
		public int DiemTichLuy
		{
			get
			{
				return this._DiemTichLuy;
			}
			set
			{
				if ((this._DiemTichLuy != value))
				{
					this.OnDiemTichLuyChanging(value);
					this.SendPropertyChanging();
					this._DiemTichLuy = value;
					this.SendPropertyChanged("DiemTichLuy");
					this.OnDiemTichLuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKhachHang", DbType="NVarChar(50)")]
		public string LoaiKhachHang
		{
			get
			{
				return this._LoaiKhachHang;
			}
			set
			{
				if ((this._LoaiKhachHang != value))
				{
					this.OnLoaiKhachHangChanging(value);
					this.SendPropertyChanging();
					this._LoaiKhachHang = value;
					this.SendPropertyChanged("LoaiKhachHang");
					this.OnLoaiKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblGiaoDich", Storage="_tblGiaoDiches", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<tblGiaoDich> tblGiaoDiches
		{
			get
			{
				return this._tblGiaoDiches;
			}
			set
			{
				this._tblGiaoDiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblLichSuGiaoDich", Storage="_tblLichSuGiaoDiches", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<tblLichSuGiaoDich> tblLichSuGiaoDiches
		{
			get
			{
				return this._tblLichSuGiaoDiches;
			}
			set
			{
				this._tblLichSuGiaoDiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblTaiKhoan", Storage="_tblTaiKhoans", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<tblTaiKhoan> tblTaiKhoans
		{
			get
			{
				return this._tblTaiKhoans;
			}
			set
			{
				this._tblTaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblGiaoDiches(tblGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblKhachHang = this;
		}
		
		private void detach_tblGiaoDiches(tblGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblKhachHang = null;
		}
		
		private void attach_tblLichSuGiaoDiches(tblLichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblKhachHang = this;
		}
		
		private void detach_tblLichSuGiaoDiches(tblLichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblKhachHang = null;
		}
		
		private void attach_tblTaiKhoans(tblTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblKhachHang = this;
		}
		
		private void detach_tblTaiKhoans(tblTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblKhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLichSuGiaoDich")]
	public partial class tblLichSuGiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLSGD;
		
		private int _TongTienGD;
		
		private int _MaGD;
		
		private int _MaKH;
		
		private EntityRef<tblGiaoDich> _tblGiaoDich;
		
		private EntityRef<tblKhachHang> _tblKhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLSGDChanging(int value);
    partial void OnMaLSGDChanged();
    partial void OnTongTienGDChanging(int value);
    partial void OnTongTienGDChanged();
    partial void OnMaGDChanging(int value);
    partial void OnMaGDChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    #endregion
		
		public tblLichSuGiaoDich()
		{
			this._tblGiaoDich = default(EntityRef<tblGiaoDich>);
			this._tblKhachHang = default(EntityRef<tblKhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLSGD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLSGD
		{
			get
			{
				return this._MaLSGD;
			}
			set
			{
				if ((this._MaLSGD != value))
				{
					this.OnMaLSGDChanging(value);
					this.SendPropertyChanging();
					this._MaLSGD = value;
					this.SendPropertyChanged("MaLSGD");
					this.OnMaLSGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTienGD", DbType="Int NOT NULL")]
		public int TongTienGD
		{
			get
			{
				return this._TongTienGD;
			}
			set
			{
				if ((this._TongTienGD != value))
				{
					this.OnTongTienGDChanging(value);
					this.SendPropertyChanging();
					this._TongTienGD = value;
					this.SendPropertyChanged("TongTienGD");
					this.OnTongTienGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGD", DbType="Int NOT NULL")]
		public int MaGD
		{
			get
			{
				return this._MaGD;
			}
			set
			{
				if ((this._MaGD != value))
				{
					if (this._tblGiaoDich.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGDChanging(value);
					this.SendPropertyChanging();
					this._MaGD = value;
					this.SendPropertyChanged("MaGD");
					this.OnMaGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tblKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGiaoDich_tblLichSuGiaoDich", Storage="_tblGiaoDich", ThisKey="MaGD", OtherKey="MaGD", IsForeignKey=true)]
		public tblGiaoDich tblGiaoDich
		{
			get
			{
				return this._tblGiaoDich.Entity;
			}
			set
			{
				tblGiaoDich previousValue = this._tblGiaoDich.Entity;
				if (((previousValue != value) 
							|| (this._tblGiaoDich.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblGiaoDich.Entity = null;
						previousValue.tblLichSuGiaoDiches.Remove(this);
					}
					this._tblGiaoDich.Entity = value;
					if ((value != null))
					{
						value.tblLichSuGiaoDiches.Add(this);
						this._MaGD = value.MaGD;
					}
					else
					{
						this._MaGD = default(int);
					}
					this.SendPropertyChanged("tblGiaoDich");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblLichSuGiaoDich", Storage="_tblKhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tblKhachHang tblKhachHang
		{
			get
			{
				return this._tblKhachHang.Entity;
			}
			set
			{
				tblKhachHang previousValue = this._tblKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tblKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhachHang.Entity = null;
						previousValue.tblLichSuGiaoDiches.Remove(this);
					}
					this._tblKhachHang.Entity = value;
					if ((value != null))
					{
						value.tblLichSuGiaoDiches.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("tblKhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLoaiSanPham")]
	public partial class tblLoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoai;
		
		private string _TenLoai;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(int value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public tblLoaiSanPham()
		{
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiSanPham_tblSanPham", Storage="_tblSanPhams", ThisKey="MaLoai", OtherKey="MaLH")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiSanPham = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhaCungCap")]
	public partial class tblNhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNCC;
		
		private string _TenNCC;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private string _Email;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(int value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public tblNhaCungCap()
		{
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblSanPham", Storage="_tblSanPhams", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhanVien")]
	public partial class tblNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private string _NamSinh;
		
		private string _Email;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private EntitySet<tblGiaoDich> _tblGiaoDiches;
		
		private EntitySet<tblTaiKhoan> _tblTaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNamSinhChanging(string value);
    partial void OnNamSinhChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public tblNhanVien()
		{
			this._tblGiaoDiches = new EntitySet<tblGiaoDich>(new Action<tblGiaoDich>(this.attach_tblGiaoDiches), new Action<tblGiaoDich>(this.detach_tblGiaoDiches));
			this._tblTaiKhoans = new EntitySet<tblTaiKhoan>(new Action<tblTaiKhoan>(this.attach_tblTaiKhoans), new Action<tblTaiKhoan>(this.detach_tblTaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this.OnNamSinhChanging(value);
					this.SendPropertyChanging();
					this._NamSinh = value;
					this.SendPropertyChanged("NamSinh");
					this.OnNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblGiaoDich", Storage="_tblGiaoDiches", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<tblGiaoDich> tblGiaoDiches
		{
			get
			{
				return this._tblGiaoDiches;
			}
			set
			{
				this._tblGiaoDiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblTaiKhoan", Storage="_tblTaiKhoans", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<tblTaiKhoan> tblTaiKhoans
		{
			get
			{
				return this._tblTaiKhoans;
			}
			set
			{
				this._tblTaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblGiaoDiches(tblGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblGiaoDiches(tblGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
		
		private void attach_tblTaiKhoans(tblTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblTaiKhoans(tblTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblQuyen")]
	public partial class tblQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQuyen;
		
		private string _TenQuyen;
		
		private EntitySet<tblTaiKhoan> _tblTaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuyenChanging(int value);
    partial void OnMaQuyenChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    #endregion
		
		public tblQuyen()
		{
			this._tblTaiKhoans = new EntitySet<tblTaiKhoan>(new Action<tblTaiKhoan>(this.attach_tblTaiKhoans), new Action<tblTaiKhoan>(this.detach_tblTaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuyen", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaQuyen
		{
			get
			{
				return this._MaQuyen;
			}
			set
			{
				if ((this._MaQuyen != value))
				{
					this.OnMaQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuyen = value;
					this.SendPropertyChanged("MaQuyen");
					this.OnMaQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenQuyen
		{
			get
			{
				return this._TenQuyen;
			}
			set
			{
				if ((this._TenQuyen != value))
				{
					this.OnTenQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuyen = value;
					this.SendPropertyChanged("TenQuyen");
					this.OnTenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblQuyen_tblTaiKhoan", Storage="_tblTaiKhoans", ThisKey="MaQuyen", OtherKey="MaQuyen")]
		public EntitySet<tblTaiKhoan> tblTaiKhoans
		{
			get
			{
				return this._tblTaiKhoans;
			}
			set
			{
				this._tblTaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblTaiKhoans(tblTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblQuyen = this;
		}
		
		private void detach_tblTaiKhoans(tblTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblQuyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSanPham")]
	public partial class tblSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSP;
		
		private string _TenSP;
		
		private int _MucGiamGia;
		
		private int _DonGia;
		
		private int _MaNCC;
		
		private int _MaLH;
		
		private EntitySet<tblSanPhamGiaoDich> _tblSanPhamGiaoDiches;
		
		private EntityRef<tblLoaiSanPham> _tblLoaiSanPham;
		
		private EntityRef<tblNhaCungCap> _tblNhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnMucGiamGiaChanging(int value);
    partial void OnMucGiamGiaChanged();
    partial void OnDonGiaChanging(int value);
    partial void OnDonGiaChanged();
    partial void OnMaNCCChanging(int value);
    partial void OnMaNCCChanged();
    partial void OnMaLHChanging(int value);
    partial void OnMaLHChanged();
    #endregion
		
		public tblSanPham()
		{
			this._tblSanPhamGiaoDiches = new EntitySet<tblSanPhamGiaoDich>(new Action<tblSanPhamGiaoDich>(this.attach_tblSanPhamGiaoDiches), new Action<tblSanPhamGiaoDich>(this.detach_tblSanPhamGiaoDiches));
			this._tblLoaiSanPham = default(EntityRef<tblLoaiSanPham>);
			this._tblNhaCungCap = default(EntityRef<tblNhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucGiamGia", DbType="Int NOT NULL")]
		public int MucGiamGia
		{
			get
			{
				return this._MucGiamGia;
			}
			set
			{
				if ((this._MucGiamGia != value))
				{
					this.OnMucGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._MucGiamGia = value;
					this.SendPropertyChanged("MucGiamGia");
					this.OnMucGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int NOT NULL")]
		public int DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="Int NOT NULL")]
		public int MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._tblNhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLH", DbType="Int NOT NULL")]
		public int MaLH
		{
			get
			{
				return this._MaLH;
			}
			set
			{
				if ((this._MaLH != value))
				{
					if (this._tblLoaiSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLHChanging(value);
					this.SendPropertyChanging();
					this._MaLH = value;
					this.SendPropertyChanged("MaLH");
					this.OnMaLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblSanPhamGiaoDich", Storage="_tblSanPhamGiaoDiches", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<tblSanPhamGiaoDich> tblSanPhamGiaoDiches
		{
			get
			{
				return this._tblSanPhamGiaoDiches;
			}
			set
			{
				this._tblSanPhamGiaoDiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiSanPham_tblSanPham", Storage="_tblLoaiSanPham", ThisKey="MaLH", OtherKey="MaLoai", IsForeignKey=true)]
		public tblLoaiSanPham tblLoaiSanPham
		{
			get
			{
				return this._tblLoaiSanPham.Entity;
			}
			set
			{
				tblLoaiSanPham previousValue = this._tblLoaiSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tblLoaiSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLoaiSanPham.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblLoaiSanPham.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._MaLH = value.MaLoai;
					}
					else
					{
						this._MaLH = default(int);
					}
					this.SendPropertyChanged("tblLoaiSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblSanPham", Storage="_tblNhaCungCap", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public tblNhaCungCap tblNhaCungCap
		{
			get
			{
				return this._tblNhaCungCap.Entity;
			}
			set
			{
				tblNhaCungCap previousValue = this._tblNhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._tblNhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhaCungCap.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblNhaCungCap.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(int);
					}
					this.SendPropertyChanged("tblNhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhamGiaoDiches(tblSanPhamGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = this;
		}
		
		private void detach_tblSanPhamGiaoDiches(tblSanPhamGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSanPhamGiaoDich")]
	public partial class tblSanPhamGiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGD;
		
		private int _MaSP;
		
		private int _SoLuong;
		
		private EntityRef<tblGiaoDich> _tblGiaoDich;
		
		private EntityRef<tblSanPham> _tblSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGDChanging(int value);
    partial void OnMaGDChanged();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    #endregion
		
		public tblSanPhamGiaoDich()
		{
			this._tblGiaoDich = default(EntityRef<tblGiaoDich>);
			this._tblSanPham = default(EntityRef<tblSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaGD
		{
			get
			{
				return this._MaGD;
			}
			set
			{
				if ((this._MaGD != value))
				{
					if (this._tblGiaoDich.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGDChanging(value);
					this.SendPropertyChanging();
					this._MaGD = value;
					this.SendPropertyChanged("MaGD");
					this.OnMaGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._tblSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGiaoDich_tblSanPhamGiaoDich", Storage="_tblGiaoDich", ThisKey="MaGD", OtherKey="MaGD", IsForeignKey=true)]
		public tblGiaoDich tblGiaoDich
		{
			get
			{
				return this._tblGiaoDich.Entity;
			}
			set
			{
				tblGiaoDich previousValue = this._tblGiaoDich.Entity;
				if (((previousValue != value) 
							|| (this._tblGiaoDich.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblGiaoDich.Entity = null;
						previousValue.tblSanPhamGiaoDiches.Remove(this);
					}
					this._tblGiaoDich.Entity = value;
					if ((value != null))
					{
						value.tblSanPhamGiaoDiches.Add(this);
						this._MaGD = value.MaGD;
					}
					else
					{
						this._MaGD = default(int);
					}
					this.SendPropertyChanged("tblGiaoDich");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblSanPhamGiaoDich", Storage="_tblSanPham", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public tblSanPham tblSanPham
		{
			get
			{
				return this._tblSanPham.Entity;
			}
			set
			{
				tblSanPham previousValue = this._tblSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tblSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSanPham.Entity = null;
						previousValue.tblSanPhamGiaoDiches.Remove(this);
					}
					this._tblSanPham.Entity = value;
					if ((value != null))
					{
						value.tblSanPhamGiaoDiches.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(int);
					}
					this.SendPropertyChanged("tblSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTaiKhoan")]
	public partial class tblTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private int _MaQuyen;
		
		private int _MaNV;
		
		private int _MaKH;
		
		private EntityRef<tblKhachHang> _tblKhachHang;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
		private EntityRef<tblQuyen> _tblQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaQuyenChanging(int value);
    partial void OnMaQuyenChanged();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    #endregion
		
		public tblTaiKhoan()
		{
			this._tblKhachHang = default(EntityRef<tblKhachHang>);
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			this._tblQuyen = default(EntityRef<tblQuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuyen", DbType="Int NOT NULL")]
		public int MaQuyen
		{
			get
			{
				return this._MaQuyen;
			}
			set
			{
				if ((this._MaQuyen != value))
				{
					if (this._tblQuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuyen = value;
					this.SendPropertyChanged("MaQuyen");
					this.OnMaQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tblKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblTaiKhoan", Storage="_tblKhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tblKhachHang tblKhachHang
		{
			get
			{
				return this._tblKhachHang.Entity;
			}
			set
			{
				tblKhachHang previousValue = this._tblKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tblKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhachHang.Entity = null;
						previousValue.tblTaiKhoans.Remove(this);
					}
					this._tblKhachHang.Entity = value;
					if ((value != null))
					{
						value.tblTaiKhoans.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("tblKhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblTaiKhoan", Storage="_tblNhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblTaiKhoans.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblTaiKhoans.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblQuyen_tblTaiKhoan", Storage="_tblQuyen", ThisKey="MaQuyen", OtherKey="MaQuyen", IsForeignKey=true)]
		public tblQuyen tblQuyen
		{
			get
			{
				return this._tblQuyen.Entity;
			}
			set
			{
				tblQuyen previousValue = this._tblQuyen.Entity;
				if (((previousValue != value) 
							|| (this._tblQuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblQuyen.Entity = null;
						previousValue.tblTaiKhoans.Remove(this);
					}
					this._tblQuyen.Entity = value;
					if ((value != null))
					{
						value.tblTaiKhoans.Add(this);
						this._MaQuyen = value.MaQuyen;
					}
					else
					{
						this._MaQuyen = default(int);
					}
					this.SendPropertyChanged("tblQuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
