//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachHang.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKHEntities : DbContext
    {
        public QLKHEntities()
            : base("name=QLKHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblGiaoDich> tblGiaoDich { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHang { get; set; }
        public virtual DbSet<tblLichSuGiaoDich> tblLichSuGiaoDich { get; set; }
        public virtual DbSet<tblLoaiSanPham> tblLoaiSanPham { get; set; }
        public virtual DbSet<tblNhaCungCap> tblNhaCungCap { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanVien { get; set; }
        public virtual DbSet<tblQuyen> tblQuyen { get; set; }
        public virtual DbSet<tblSanPham> tblSanPham { get; set; }
        public virtual DbSet<tblSanPhamGiaoDich> tblSanPhamGiaoDich { get; set; }
        public virtual DbSet<tblTaiKhoan> tblTaiKhoan { get; set; }
    }
}
