//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLichSuGiaoDich
    {
        public int MaLSGD { get; set; }
        public int TongTienGD { get; set; }
        public int MaGD { get; set; }
        public int MaKH { get; set; }
    
        public virtual tblGiaoDich tblGiaoDich { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
    }
}
