//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanPhamGiaoDich
    {
        public int MaGD { get; set; }
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
    
        public virtual tblSanPham tblSanPham { get; set; }
        public virtual tblGiaoDich tblGiaoDich { get; set; }
    }
}
